# Generated by Django 5.0.6 on 2026-09-12 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_attendance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('present', 'Present'), ('late', 'Late'), ('absent', 'Absent'), ('on_leave', 'On Leave'), ('day_off', 'Day Off')], default='present', max_length=20),
        ),
    ]
